"""Generate paper-facing table artifacts from existing result CSVs."""

import argparse
import csv
from pathlib import Path


DEFAULT_SOURCE = Path("results/execution_mismatch/final_execution_baseline_summary.csv")
DEFAULT_TABLE1_CSV = Path("results/paper/table1_main_results.csv")
DEFAULT_TABLE1_MD = Path("docs/PAPER_TABLE1_MAIN_RESULTS.md")

TABLE1_METHOD_ORDER = [
    "Rotating B=8",
    "Sparse-TopK B=4 sm=3",
    "Coverage-Aware B=4 cw=0.5 cpw=0",
    "Coverage-Aware B=3 sm=4.1 cw=0.5 cpw=0",
    "Mask-Corrected Coverage-Aware B=3 mc=1",
    "Stale-TopK B=4",
    "Temporal Deviation Oracle B=4",
]

TABLE1_COLUMNS = ["Method", "Role", "Slots", "Failed", "Missed", "Preview", "Gap"]


def read_rows(path):
    with path.open(newline="", encoding="utf-8") as csvfile:
        return list(csv.DictReader(csvfile))


def row_by_label(rows, label):
    matches = [row for row in rows if row.get("label") == label]
    if not matches:
        raise ValueError(f"missing required Table 1 method: {label}")
    if len(matches) > 1:
        raise ValueError(f"ambiguous Table 1 method: {label}")
    return matches[0]


def format_row(row):
    return {
        "Method": row["label"],
        "Role": row["role"],
        "Slots": f"{float(row['slots_mean']):.3f}",
        "Failed": f"{float(row['failed_nodes_mean']):.3f}",
        "Missed": f"{float(row['missed_opportunities_mean']):.3f}",
        "Preview": f"{float(row['decision_preview_calls_per_slot_mean']):.2f}",
        "Gap": f"{float(row['oracle_tx_gap_mean']):.3f}",
    }


def build_table1(source_rows):
    return [format_row(row_by_label(source_rows, label)) for label in TABLE1_METHOD_ORDER]


def write_csv(path, rows):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as csvfile:
        writer = csv.DictWriter(csvfile, fieldnames=TABLE1_COLUMNS)
        writer.writeheader()
        writer.writerows(rows)


def markdown_table(rows):
    lines = [
        "| Method | Role | Slots | Failed | Missed | Preview | Gap |",
        "|---|---|---:|---:|---:|---:|---:|",
    ]
    for row in rows:
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{row['Method']}`",
                    row["Role"],
                    row["Slots"],
                    row["Failed"],
                    row["Missed"],
                    row["Preview"],
                    row["Gap"],
                ]
            )
            + " |"
        )
    return "\n".join(lines)


def write_markdown(path, rows, source_path, csv_path):
    path.parent.mkdir(parents=True, exist_ok=True)
    content = f"""# Paper Table 1 Main Results

This file is generated by `generate_paper_tables.py`. Do not edit table values by hand; update the source CSV or generator instead.

Source: `{source_path}`

Generated CSV: `{csv_path}`

## Table

{markdown_table(rows)}

## Caption

Table 1. Main execution-mismatch results averaged over 9 temporal AR(1) stale-CSI scenarios. The proposed mask-corrected coverage-aware method keeps the same preview budget as the uncorrected coverage-aware baseline but reduces both failed invitations and missed opportunities. The temporal-deviation oracle is a hidden-information diagnostic upper bound, not a deployable method.

## Notes

- Method order follows `docs/PAPER_FIGURE_TABLE_SPECS.md`.
- `Rotating B=4`, Adaptive V2 continuum points and learned variants are excluded from the paper-facing main table.
- `Perfect %` is omitted from the compact main table because it is near-saturated; failed, missed, preview and gap carry the main mechanism evidence.
"""
    path.write_text(content, encoding="utf-8")


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--table1-csv", type=Path, default=DEFAULT_TABLE1_CSV)
    parser.add_argument("--table1-md", type=Path, default=DEFAULT_TABLE1_MD)
    return parser.parse_args()


def main():
    args = parse_args()
    source_rows = read_rows(args.source)
    table1_rows = build_table1(source_rows)
    write_csv(args.table1_csv, table1_rows)
    write_markdown(args.table1_md, table1_rows, args.source, args.table1_csv)
    print(f"wrote {args.table1_csv}")
    print(f"wrote {args.table1_md}")


if __name__ == "__main__":
    main()
